export const projects = [
  {
    id: "1",
    titleTr: "Kurumsal Portal",
    titleEn: "Corporate Portal",
    summaryTr: "Çok dilli kurumsal web sitesi ve yönetim paneli.",
    summaryEn: "Multilingual corporate website and admin panel.",
    stack: ["Next.js", "TypeScript", "Tailwind"],
    detailTr: "Müşteri için özel tasarlanmış kurumsal portal. TR/EN dil desteği, blog ve iletişim modülleri.",
    detailEn: "Custom corporate portal. TR/EN language support, blog and contact modules.",
  },
  {
    id: "2",
    titleTr: "E-Ticaret Mağazası",
    titleEn: "E-Commerce Store",
    summaryTr: "WooCommerce tabanlı online mağaza.",
    summaryEn: "WooCommerce-based online store.",
    stack: ["WordPress", "WooCommerce", "PHP"],
    detailTr: "Ürün kataloğu, sepet, ödeme entegrasyonu ve sipariş yönetimi.",
    detailEn: "Product catalog, cart, payment integration and order management.",
  },
  {
    id: "3",
    titleTr: "SaaS Dashboard",
    titleEn: "SaaS Dashboard",
    summaryTr: "Analitik ve raporlama paneli.",
    summaryEn: "Analytics and reporting dashboard.",
    stack: ["React", "Node.js", "PostgreSQL"],
    detailTr: "Gerçek zamanlı metrikler, grafikler ve kullanıcı yönetimi.",
    detailEn: "Real-time metrics, charts and user management.",
  },
  {
    id: "4",
    titleTr: "Landing Page Kampanyası",
    titleEn: "Landing Page Campaign",
    summaryTr: "Reklam kampanyası için yüksek dönüşüm sayfası.",
    summaryEn: "High-conversion page for ad campaign.",
    stack: ["Next.js", "Tailwind", "Vercel"],
    detailTr: "A/B test altyapılı, hızlı yükleme ve form entegrasyonu.",
    detailEn: "A/B test infrastructure, fast load and form integration.",
  },
  {
    id: "5",
    titleTr: "Mobil Uygulama",
    titleEn: "Mobile App",
    summaryTr: "Android uygulama (hybrid).",
    summaryEn: "Android app (hybrid).",
    stack: ["React Native", "Android"],
    detailTr: "Mevcut web API ile entegre mobil uygulama.",
    detailEn: "Mobile app integrated with existing web API.",
  },
  {
    id: "6",
    titleTr: "API Entegrasyonu",
    titleEn: "API Integration",
    summaryTr: "Üçüncü parti servis entegrasyonları.",
    summaryEn: "Third-party service integrations.",
    stack: ["Node.js", "REST", "Webhooks"],
    detailTr: "CRM, e-posta ve ödeme sistemleri ile entegrasyon.",
    detailEn: "Integration with CRM, email and payment systems.",
  },
  {
    id: "7",
    titleTr: "Blog Platformu",
    titleEn: "Blog Platform",
    summaryTr: "İçerik yönetimli blog sitesi.",
    summaryEn: "CMS-powered blog site.",
    stack: ["Next.js", "MDX", "Vercel"],
    detailTr: "MDX destekli, arama ve kategoriler.",
    detailEn: "MDX support, search and categories.",
  },
  {
    id: "8",
    titleTr: "Portföy Sitesi",
    titleEn: "Portfolio Site",
    summaryTr: "Minimal portföy ve proje galerisi.",
    summaryEn: "Minimal portfolio and project gallery.",
    stack: ["Next.js", "Tailwind", "Framer Motion"],
    detailTr: "Animasyonlu proje kartları ve iletişim formu.",
    detailEn: "Animated project cards and contact form.",
  },
] as const;

export type Project = (typeof projects)[number];
