export const services = [
  {
    id: "1",
    titleKey: "nextjs",
    titleTr: "Next.js Web Apps",
    titleEn: "Next.js Web Apps",
    descTr: "Modern, hızlı ve SEO dostu web uygulamaları.",
    descEn: "Modern, fast and SEO-friendly web applications.",
    tags: ["Next.js", "React", "TypeScript"],
    icon: "⚛️",
    iconColor: "rgba(96,165,250,0.95)",
  },
  {
    id: "2",
    titleKey: "wordpress",
    titleTr: "WordPress Websites",
    titleEn: "WordPress Websites",
    descTr: "Kurumsal ve e-ticaret siteleri.",
    descEn: "Corporate and e-commerce websites.",
    tags: ["WordPress", "WooCommerce"],
    icon: "🧩",
    iconColor: "rgba(167,139,250,0.95)",
  },
  {
    id: "3",
    titleKey: "saas",
    titleTr: "SaaS Dashboards",
    titleEn: "SaaS Dashboards",
    descTr: "Özel yönetim panelleri ve dashboard'lar.",
    descEn: "Custom admin panels and dashboards.",
    tags: ["React", "Node", "API"],
    icon: "📊",
    iconColor: "rgba(52,211,153,0.95)",
  },
  {
    id: "4",
    titleKey: "uiux",
    titleTr: "UI/UX Design",
    titleEn: "UI/UX Design",
    descTr: "Kullanıcı odaklı arayüz tasarımı.",
    descEn: "User-centered interface design.",
    tags: ["Figma", "Prototype"],
    icon: "🎨",
    iconColor: "rgba(250,204,21,0.95)",
  },
  {
    id: "5",
    titleKey: "php",
    titleTr: "PHP Websites",
    titleEn: "PHP Websites",
    descTr: "Özelleştirilmiş PHP tabanlı projeler.",
    descEn: "Custom PHP-based projects.",
    tags: ["PHP", "Laravel"],
    icon: "⚙️",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "6",
    titleKey: "android",
    titleTr: "Android Apps",
    titleEn: "Android Apps",
    descTr: "Native ve hybrid mobil uygulamalar.",
    descEn: "Native and hybrid mobile apps.",
    tags: ["Android", "Kotlin"],
    icon: "📱",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "7",
    titleKey: "landing",
    titleTr: "Landing Pages",
    titleEn: "Landing Pages",
    descTr: "Dönüşüm odaklı tek sayfa tasarımlar.",
    descEn: "Conversion-focused single-page designs.",
    tags: ["Landing", "Conversion"],
    icon: "📄",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "8",
    titleKey: "seo",
    titleTr: "SEO & Performance",
    titleEn: "SEO & Performance",
    descTr: "Arama motoru ve hız optimizasyonu.",
    descEn: "Search engine and speed optimization.",
    tags: ["SEO", "Core Web Vitals"],
    icon: "📈",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "9",
    titleKey: "automation",
    titleTr: "Automation",
    titleEn: "Automation",
    descTr: "Make, Zapier ve özel entegrasyonlar.",
    descEn: "Make, Zapier and custom integrations.",
    tags: ["Make", "Zapier", "API"],
    icon: "🔄",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "10",
    titleKey: "maintenance",
    titleTr: "Maintenance & Support",
    titleEn: "Maintenance & Support",
    descTr: "Bakım, güncelleme ve teknik destek.",
    descEn: "Maintenance, updates and technical support.",
    tags: ["Support", "Updates"],
    icon: "🛠️",
    iconColor: "rgba(255,255,255,0.85)",
  },
] as const;
