export const services = [
  {
    id: "1",
    titleKey: "operationPanels",
    titleTr: "Operasyon panelleri",
    titleEn: "Operations control panels",
    descTr: "Saha ve ofis için tek doğru ekran: iş akışı, durum ve kararlar tek sistemde toplanır.",
    descEn: "One operational surface for field and office — workflows, status, and decisions in a single system.",
    tags: ["Next.js", "RBAC", "Live views"],
    icon: "◎",
    iconColor: "rgba(96,165,250,0.9)",
  },
  {
    id: "2",
    titleKey: "internalAdmin",
    titleTr: "İç araçlar ve yönetim sistemleri",
    titleEn: "Internal tools & admin systems",
    descTr: "Onay, kayıt ve iç süreçler için kalıcı yazılım; tabloların yerini net veri modeli alır.",
    descEn: "Purpose-built software for approvals, records, and internal process — structured data instead of spreadsheet chaos.",
    tags: ["TypeScript", "APIs", "Workflow"],
    icon: "⬡",
    iconColor: "rgba(52,211,153,0.9)",
  },
  {
    id: "3",
    titleKey: "analyticsDash",
    titleTr: "Performans ve analiz panoları",
    titleEn: "Performance & analytics dashboards",
    descTr: "KPI, trend ve drill-down ile yönetime ölçülebilir görünürlük; ham veriyi aksiyona çevirir.",
    descEn: "KPIs, trends, and drill-downs leadership can trust — turning raw signals into operational clarity.",
    tags: ["Metrics", "Reporting", "Data viz"],
    icon: "◈",
    iconColor: "rgba(129,140,248,0.9)",
  },
  {
    id: "4",
    titleKey: "productSurfaces",
    titleTr: "Ürün arayüzleri ve kullanıcı yüzeyleri",
    titleEn: "Product UI & customer-facing surfaces",
    descTr: "Müşteri ve kullanıcıya dönük uygulama akışları; tasarım sistemiyle tutarlı, ölçeklenebilir arayüz.",
    descEn: "Customer-facing apps and flows — consistent, scalable UI grounded in a shared design system.",
    tags: ["React", "UX systems", "a11y"],
    icon: "◇",
    iconColor: "rgba(250,204,21,0.88)",
  },
  {
    id: "5",
    titleKey: "integrations",
    titleTr: "Entegrasyon ve otomasyon",
    titleEn: "Integrations & automation",
    descTr: "API, webhook ve olay tabanlı bağlantılar; araçlarınızın birbirini gerçek zamanlı tetiklemesi.",
    descEn: "APIs, webhooks, and event-driven wiring so your stack reacts in real time, not in manual batches.",
    tags: ["REST", "Webhooks", "Events"],
    icon: "↔",
    iconColor: "rgba(148,163,184,0.85)",
  },
  {
    id: "6",
    titleKey: "contentLayer",
    titleTr: "İçerik ve katalog katmanları",
    titleEn: "Content & catalog layers",
    descTr: "Editoryal veya ürün katalogu gerektiğinde olgun içerik modeli; gerektiğinde klasik CMS ile desteklenir.",
    descEn: "Editorial or product-catalog needs with a mature content model — classic CMS only when it genuinely fits.",
    tags: ["Headless", "WordPress", "Commerce"],
    icon: "▦",
    iconColor: "rgba(167,139,250,0.75)",
  },
  {
    id: "7",
    titleKey: "reliability",
    titleTr: "Güvenilirlik ve gözlemlenebilirlik",
    titleEn: "Reliability & observability",
    descTr: "Performans, güvenlik ve izleme; üretimdeki sistemlerin ölçülebilir ve sürdürülebilir kalması.",
    descEn: "Performance hardening, security hygiene, and monitoring so production systems stay measurable and maintainable.",
    tags: ["Caching", "SLOs", "Logs"],
    icon: "◉",
    iconColor: "rgba(148,163,184,0.8)",
  },
  {
    id: "8",
    titleKey: "lifecycle",
    titleTr: "Yaşam döngüsü ve evrim",
    titleEn: "Lifecycle & evolution",
    descTr: "Yayın sonrası iterasyon, sürümleme ve küçük genişlemeler; ürün işinizle birlikte büyür.",
    descEn: "Post-launch iteration, releases, and scoped extensions — software that evolves with how you operate.",
    tags: ["CI/CD", "Support", "Roadmap"],
    icon: "↻",
    iconColor: "rgba(148,163,184,0.75)",
  },
] as const;
