export const services = [
  {
    id: "1",
    titleKey: "nextjs",
    titleTr: "Next.js ürün yüzeyleri",
    titleEn: "Next.js product surfaces",
    descTr: "Tam yığın web uygulamaları, müşteri portalları ve pazarlama yüzeyleri; performans ve SEO varsayılan.",
    descEn: "Full-stack web apps, customer portals, and marketing surfaces — performance and SEO as defaults.",
    tags: ["Next.js", "React", "TypeScript"],
    icon: "⚛️",
    iconColor: "rgba(96,165,250,0.95)",
  },
  {
    id: "2",
    titleKey: "wordpress",
    titleTr: "İçerik ve ticaret katmanı",
    titleEn: "Content & commerce layer",
    descTr: "Editoryal veya katalog iş akışları olgun bir CMS gerektirdiğinde WordPress ve WooCommerce.",
    descEn: "WordPress and WooCommerce when editorial or catalog workflows need a mature CMS.",
    tags: ["WordPress", "WooCommerce"],
    icon: "🧩",
    iconColor: "rgba(167,139,250,0.95)",
  },
  {
    id: "3",
    titleKey: "saas",
    titleTr: "SaaS ve yönetim konsolları",
    titleEn: "SaaS & admin consoles",
    descTr: "Rol tabanlı paneller, iç araçlar ve ekiplerinizin her gün kullandığı veri ağırlıklı arayüzler.",
    descEn: "Role-based dashboards, internal tools, and data-heavy UIs your teams use every day.",
    tags: ["React", "Node", "API"],
    icon: "📊",
    iconColor: "rgba(52,211,153,0.95)",
  },
  {
    id: "4",
    titleKey: "uiux",
    titleTr: "Ürün arayüzü ve tasarım sistemi",
    titleEn: "Product UI & design systems",
    descTr: "Mühendislik kısıtlarıyla uyumlu arayüz mimarisi ve yeniden kullanılabilir bileşenler.",
    descEn: "Interface architecture and reusable components aligned with engineering constraints.",
    tags: ["Figma", "Prototype"],
    icon: "🎨",
    iconColor: "rgba(250,204,21,0.95)",
  },
  {
    id: "5",
    titleKey: "php",
    titleTr: "Özel backend (PHP)",
    titleEn: "Custom backends (PHP)",
    descTr: "API’ler, entegrasyonlar ve Laravel veya özelleştirilmiş PHP yığınlarıyla miras modernizasyonu.",
    descEn: "APIs, integrations, and legacy modernization on Laravel or tailored PHP stacks.",
    tags: ["PHP", "Laravel"],
    icon: "⚙️",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "6",
    titleKey: "android",
    titleTr: "Android istemcileri",
    titleEn: "Android clients",
    descTr: "Yerel Android’in doğru olduğu yardımcı uygulamalar ve saha araçları.",
    descEn: "Companion apps and field tools where native Android is the right fit.",
    tags: ["Android", "Kotlin"],
    icon: "📱",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "7",
    titleKey: "landing",
    titleTr: "Yüksek niyetli landing yapıları",
    titleEn: "High-intent landing systems",
    descTr: "Ölçüm için tasarlanmış odaklı huniler ve lansman sayfaları — süs için değil.",
    descEn: "Focused funnels and launch pages engineered for measurement, not decoration.",
    tags: ["Landing", "Conversion"],
    icon: "📄",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "8",
    titleKey: "seo",
    titleTr: "Performans ve güvenilirlik",
    titleEn: "Performance & reliability",
    descTr: "Core Web Vitals, önbellekleme ve gözlemlenebilirlik; sistemler yük altında hızlı kalsın.",
    descEn: "Core Web Vitals, caching, and observability so systems stay fast under load.",
    tags: ["SEO", "Core Web Vitals"],
    icon: "📈",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "9",
    titleKey: "automation",
    titleTr: "İş akışı otomasyonu",
    titleEn: "Workflow automation",
    descTr: "API’ler, webhook’lar ve Make/Zapier ile yığınınızı uçtan uca bağlama.",
    descEn: "APIs, webhooks, and tools like Make/Zapier to connect your stack end to end.",
    tags: ["Make", "Zapier", "API"],
    icon: "🔄",
    iconColor: "rgba(255,255,255,0.85)",
  },
  {
    id: "10",
    titleKey: "maintenance",
    titleTr: "Yaşam döngüsü desteği",
    titleEn: "Lifecycle support",
    descTr: "Güncelleme, sağlamlaştırma ve iterasyon; üretimdeki sistemler işinizle birlikte evrilsin.",
    descEn: "Updates, hardening, and iteration so production systems keep pace with your business.",
    tags: ["Support", "Updates"],
    icon: "🛠️",
    iconColor: "rgba(255,255,255,0.85)",
  },
] as const;
